### PR TITLE
add liga

### PR DESCRIPTION
**Pull request by lanikaling**
The liga files are uploaded, with some bug (due to version compatibility) fixed. Readme is updated. @sbillinge

### CODE REVIEW

**Comment by pavoljuhas** [comment]
Can you please replace this with entire git history as I sent in the email?

**Comment by lanikaling** [comment]
Sure! I have replaced the last commit with the one you sent me.

**Comment by pavoljuhas** [comment]
Thank you Ling, but I think it would be good to preserve the git history as it was so it is possible to see what changes were done together and why.  

git can be initially quite confusing - would you mind if I prepare a replacement PR later today?

BTW, the `.DS_Store`, `.sconsign.dblite` and all files in `.sconf_temp` and `build` directories are temporary derived files and should not be included in the repository.  Some of these should be covered by the .gitignore file in the initial code.  For the `.DS_Store` files it is good to use a global gitignore which excludes them by default.

**Comment by lanikaling** [comment]
No problem! Thank you for telling me -- I am learning these "common sense" these days :)

**Comment by pavoljuhas** [comment]
@sbillinge, @lanikaling - done.  I have rebased (re-applied) Simon's commits on top of the previous code history.
This is normally not supposed to be done, because it rewrote the entire history of the main branch (ie, Simon's 2 commits are not included as they originally were), but I think in this case it was acceptable as a one-time action to initialize the GH repository.  I have also added 4 tags (v1.0, v1.1, v1.2, v1.2.1) that were in the original group-only repository.

For sake of safety I have stored the initial main branch as a new branch `main-tmp-backup`.  This can be deleted If you are OK with the updated `main` branch as is.

Otherwise, please make sure any new work is started from the updated main (commit a5ba35e836bad2af11db3cb05dd613bdb6dd0722 or its descendants) and not from its previous state.

If you have an *unmodified* clone of this repo, you can sync it to the updated main using
```
git fetch origin
git reset --hard origin/main
```

If you made some changes - modified files / created new commits - the safest is to clone this repository in a new folder and just reapply any changes there.

Hope this works.

**Comment by lanikaling** [comment]
Thank you so much, Pavol! It looks nice!

**Comment by sbillinge** [comment]
yes, thanks so much @pavoljuhas .  It is really exciting to have this on GitHub!  I wish we had GitHub back when the code was written!

**Pull request closed without merging**
